name: TOC Generator

on:
  pull_request:
    paths:
      - '*.md'
      - '**/*.md'

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-18.04
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: "README.md,docs/*.md"
          TOC_TITLE: ""
          MAX_HEADER_LEVEL: 4
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COMMIT_MESSAGE: "Generate Table of Contents in markdown files with GitHub Actions"
