name: Test the GitHub Actions on dbt Core

on:
  pull_request:
    paths:
      - .github/workflows/test-action-core.yml
      - action/**/*
      - integration_tests/models/**/schema.yml

# We can run either of `test-action-fusion` and `test-action-core` simultaneously.
concurrency:
  group: test-action-${{ github.head_ref }}
  cancel-in-progress: false

jobs:
  notice-start-of-test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR start of test on dbt Core
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          body=$(cat <<EOF
          ðŸš€ Starting the test action on dbt Core...
          Please check the workflow run for more details.
          URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF
          )
          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "${body}" \
            --repo "${{ github.repository }}"

  test-action:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        include:
          - python-version: "3.11"
            pip-requirements: "requirements-1.10.txt"
          - python-version: "3.11"
            pip-requirements: "requirements-1.11.txt"
          # Python 3.12
          - python-version: "3.12"
            pip-requirements: "requirements-1.10.txt"
          - python-version: "3.12"
            pip-requirements: "requirements-1.11.txt"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: "${{ github.head_ref }}"
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/${{ matrix.pip-requirements }}'
      - name: Install dbt Core
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          pip install -r "requirements/${{ matrix.pip-requirements }}"
      - name: Install dbt Packages
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt deps --target bigquery
      - name: Test the action on dbt Core
        id: test-action
        uses: ./action
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          working_directory: "${{ github.workspace }}/integration_tests"
          dbt_profiles_dir: "${{ github.workspace }}/integration_tests/profiles"
          dbt_models_dir: "${{ github.workspace }}/integration_tests/models"
          dbt_profile: "default"
          dbt_target: "bigquery"
          dbt_vars_path: "${{ github.workspace }}/integration_tests/resources/vars/vars-bigquery.basic.yml"
          delete_before: "1"
          verbose: "1"
      - name: Delete .gitignore for the generated models
        shell: bash
        run: |
          rm -f "${{ github.workspace }}/integration_tests/models/.gitignore"
      - name: Push and revert the generated models
        shell: bash
        if: ${{ steps.test-action.generated-models-count }} != '0'
        run: |
          # Confiture the git account
          git remote set-url origin "https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Push the generated models
          git add "${{ github.workspace }}/integration_tests/models"
          git commit --signoff -m 'Generate dbt models by dbt-data-privacy (dbt Core)'
          git push --set-upstream origin "HEAD:${{ github.head_ref }}"
          # Revert the commit
          git revert HEAD
          git push --force --set-upstream origin "HEAD:${{ github.head_ref }}"

  report-result:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    needs: test-action
    steps:
      - name: Comment on PR failure
        if: ${{ needs.test-action.result == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "âŒ One or more matrix jobs failed. Please check the workflow run for more details." \
            --repo "${{ github.repository }}" \
      - name: Comment on PR failure
        if: ${{ needs.test-action.result == 'success' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "âœ… All matrix jobs passed. Please check the workflow run for more details." \
            --repo "${{ github.repository }}" \
